package com.forgefit.android.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF6750A4)
val PrimaryContainer = Color(0xFFEADDFF)
val Secondary = Color(0xFF625B71)
val SecondaryContainer = Color(0xFFE8DEF8)
val Tertiary = Color(0xFF7D5260)
val TertiaryContainer = Color(0xFFFFD8E4)
val Error = Color(0xFFB3261E)
val ErrorContainer = Color(0xFFF9DEDC)
val Background = Color(0xFFFFFBFE)
val Surface = Color(0xFFFFFBFE)
val OnPrimary = Color(0xFFFFFFFF)
val OnPrimaryContainer = Color(0xFF21005D)
val OnSecondary = Color(0xFFFFFFFF)
val OnSecondaryContainer = Color(0xFF1D192B)
val OnTertiary = Color(0xFFFFFFFF)
val OnTertiaryContainer = Color(0xFF31111D)
val OnError = Color(0xFFFFFFFF)
val OnErrorContainer = Color(0xFF410E0B)
val OnBackground = Color(0xFF1C1B1F)
val OnSurface = Color(0xFF1C1B1F)

val DarkPrimary = Color(0xFFD0BCFF)
val DarkPrimaryContainer = Color(0xFF4F378B)
val DarkSecondary = Color(0xFFCCC2DC)
val DarkSecondaryContainer = Color(0xFF4A4458)
val DarkTertiary = Color(0xFFEFB8C8)
val DarkTertiaryContainer = Color(0xFF633B48)
val DarkError = Color(0xFFF2B8B5)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkBackground = Color(0xFF1C1B1F)
val DarkSurface = Color(0xFF1C1B1F)
val DarkOnPrimary = Color(0xFF381E72)
val DarkOnPrimaryContainer = Color(0xFFEADDFF)
val DarkOnSecondary = Color(0xFF332D41)
val DarkOnSecondaryContainer = Color(0xFFE8DEF8)
val DarkOnTertiary = Color(0xFF492532)
val DarkOnTertiaryContainer = Color(0xFFFFD8E4)
val DarkOnError = Color(0xFF601410)
val DarkOnErrorContainer = Color(0xFFF9DEDC)
val DarkOnBackground = Color(0xFFE6E1E5)
val DarkOnSurface = Color(0xFFE6E1E5)
